# docker-compose.mac.yml (맥북용 - bridge 네트워크)
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: matchnow-nestjs-mac
    restart: unless-stopped
    ports:
      - "4011:4011"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - PORT=4011
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - matchnow-network

  nginx:
    image: nginx:alpine
    container_name: matchnow-nginx-mac
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx-bridge.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nestjs-app
    networks:
      - matchnow-network

networks:
  matchnow-network:
    driver: bridge